[package]
name = "gosh-zk-snark-halo2-utils"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
halo2-base = { git = "https://github.com/gosh-sh/halo2-lib-zkevm-sha256-and-bls12-381", branch = "bump-halo2-lib-v0.4.1", default-features = false, features = ["halo2-axiom"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"

[dev-dependencies]
halo2-base = { git = "https://github.com/gosh-sh/halo2-lib-zkevm-sha256-and-bls12-381", branch = "bump-halo2-lib-v0.4.1", default-features = false, features = ["halo2-axiom", "test-utils"] }
gosh-dense-balanced-tree = { git = "https://github.com/gosh-sh/gosh-halo2-crypto-lib", branch = "main" }
dex-halo2-circuit = { git = "https://github.com/gosh-sh/dexdo-halo2-kit", branch = "main" }
tvm_block = { git = "https://github.com/tvmlabs/tvm-sdk", package = "tvm_block" }
hex = "0.4"

[patch.crates-io]
halo2-base = { git = "https://github.com/gosh-sh/halo2-lib-zkevm-sha256-and-bls12-381", branch = "bump-halo2-lib-v0.4.1" }

[profile.dev]
opt-level = 3

